import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),

  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      '.storage/**',
      'src/generated/**',
      // Generated by Next on every build and gitignored — not ours to lint.
      'next-env.d.ts',
    ],
  },

  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      'no-console': 'off',
      eqeqeq: ['error', 'smart'],
      'prefer-const': 'error',
    },
  },

  /**
   * Architectural boundary, enforced rather than remembered.
   *
   * docs/06-frontend.md J: `src/lib` may be imported by anything; `src/server`
   * may be imported by nothing outside `src/server` and `src/app/api`;
   * `src/components` never imports `src/server`.
   *
   * Without this rule a single stray import pulls the Prisma client — and the
   * database URL — into a client bundle.
   */
  {
    files: ['src/components/**/*.{ts,tsx}', 'src/features/**/*.{ts,tsx}', 'src/lib/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/server/*', '@/server', '**/server/**'],
              message:
                'Client-side code must not import from src/server. Fetch through the API, or move the logic into a feature-level server component.',
            },
            {
              group: ['@prisma/client'],
              message: 'Prisma is server-only. Import the types you need from a shared types module instead.',
            },
          ],
        },
      ],
    },
  },

  /**
   * Only src/server/config/env.ts may read process.env. Everything else takes
   * the parsed, validated `env` object, so a missing key fails at boot with a
   * readable message rather than as `undefined` at request time.
   */
  {
    files: ['src/**/*.{ts,tsx}', 'worker/**/*.ts'],
    ignores: [
      'src/server/config/env.ts',
      // Edge middleware cannot import env.ts — it is `server-only`, and
      // validating database and storage configuration has no meaning in an
      // isolate that can reach neither. It reads AUTH_SECRET and nothing else,
      // and fails loudly when it is absent. See the comment in the file.
      'src/middleware.ts',
    ],
    rules: {
      'no-restricted-properties': [
        'error',
        {
          object: 'process',
          property: 'env',
          message: 'Read configuration from `@/server/config/env` — env.ts is the only process.env reader.',
        },
      ],
    },
  },
];

export default config;
