import 'server-only';
import { mkdir, readFile, writeFile, unlink, access } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import { env } from '@/server/config/env';
import type { PutInput, StorageProvider, StoredObject } from './types';

/**
 * Filesystem storage, for development and tests.
 *
 * Writes under `STORAGE_LOCAL_DIR` (`./.storage`), which is gitignored and
 * sits OUTSIDE `public/` — nothing here is reachable over HTTP. Next only
 * serves `public/`, so the one way to a file's bytes is the authenticated
 * download route.
 *
 * The production guardrail in env.ts refuses `STORAGE_PROVIDER=local`,
 * because a container filesystem does not survive a restart and a municipal
 * record must.
 */
export class LocalStorageProvider implements StorageProvider {
  readonly name = 'local';
  readonly configured = true;

  private readonly root: string;

  constructor(rootDir: string = (process.env.VERCEL ? '/tmp/.storage' : env.storageLocalDir)) {
    this.root = process.env.VERCEL ? '/tmp/.storage' : resolve(process.cwd(), rootDir);
  }

  /**
   * Resolves a key to an absolute path, refusing anything that escapes the
   * root.
   *
   * Keys are generated by `buildStorageKey()` and never accepted from a
   * client, so `../../etc/passwd` should be unreachable — but "should be" is
   * not a control. This makes traversal impossible rather than merely
   * unlikely, which is the difference that matters if a future caller is ever
   * less careful than today's.
   */
  private pathFor(key: string): string {
    const full = resolve(this.root, key);
    if (full !== this.root && !full.startsWith(this.root + sep)) {
      throw new Error(`Refusing a storage key that escapes the storage root: ${key}`);
    }
    return full;
  }

  async put(input: PutInput): Promise<StoredObject> {
    const path = this.pathFor(input.key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, input.body);
    return { key: input.key, sizeBytes: input.body.byteLength };
  }

  async get(key: string): Promise<Buffer> {
    return readFile(this.pathFor(key));
  }

  async exists(key: string): Promise<boolean> {
    try {
      await access(this.pathFor(key));
      return true;
    } catch {
      return false;
    }
  }

  async remove(key: string): Promise<void> {
    try {
      await unlink(this.pathFor(key));
    } catch (err) {
      // Already gone is the desired end state, not an error.
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
    }
  }

  /** Absolute path of the storage root. Used by tests to clean up. */
  get rootDir(): string {
    return this.root;
  }

  /** Test helper: the directory a given application's files live under. */
  dirFor(applicationId: string): string {
    return join(this.root, 'applications', applicationId);
  }
}
